import Foundation

/// Generates a `main.swift` entry point that instantiates discovered rules and runs Sentinel.
struct MainGenerator {

    /// Generate main.swift source code.
    ///
    /// - Parameters:
    ///   - ruleTypeNames: Names of Rule-conforming types to instantiate.
    ///   - projectPath: Absolute path to the project being analyzed.
    ///   - excludePaths: Paths to exclude from analysis.
    ///   - includePaths: Paths to include in analysis.
    ///   - changedFiles: Absolute paths of changed files to restrict analysis to.
    /// - Returns: Generated Swift source code string.
    static func generate(
        ruleTypeNames: [String],
        projectPath: String,
        excludePaths: [String],
        includePaths: [String],
        changedFiles: [String] = []
    ) -> String {
        let ruleInstances = ruleTypeNames
            .map { "    \($0)()," }
            .joined(separator: "\n")

        let excludeArray = excludePaths
            .map { "\"\($0)\"" }
            .joined(separator: ", ")

        let includeArray = includePaths
            .map { "\"\($0)\"" }
            .joined(separator: ", ")

        let changedFilesArray = changedFiles
            .map { "\"\($0.replacingOccurrences(of: "\"", with: "\\\""))\"" }
            .joined(separator: ", ")

        return """
        // Auto-generated by Sentinel — do not edit
        import SentinelKit

        let rules: [any Rule] = [
        \(ruleInstances)
        ]

        SentinelRunner.run(
            rules: rules,
            configuration: Configuration(
                projectPath: \"\(projectPath.replacingOccurrences(of: "\"", with: "\\\""))\",
                includePaths: [\(includeArray)],
                excludePaths: [\(excludeArray)],
                changedFiles: [\(changedFilesArray)]
            )
        )
        """
    }
}
